Change landing page to be `profiling-results`
UCL/TLOmodel-profiling pull request #16
Opened 2024-05-20 13:06 UTC by willGraham01

Changes the index page of the profiling site to redirect to the `profiling-results` page by default.

Note that the current `index.rst` contents have been moved to `contents.rst` so that the `sphinx-build` still works. This change just means that the `index.html` page immediately sends a person to the profiling results.

2024-05-21 15:27 UTC, matt-graham reviewed
Do we need to have the redirect here? Could we not just keep the current index page but include the table of results within that page? 

In the docs on the main `TLOmodel` repository we generally follow the pattern of having any machine generated reStructuredText files having underscored prefixed names (and not being version controlled) with these files then included in some other reStructuredText file using the `.. include::` directive, for example [here](https://github.com/UCL/TLOmodel/blob/67c80589a2e0f274ac12c87cd76876df3010d51d/docs/data_sources.rst?plain=1#L9C1-L9C13) and [here](https://github.com/UCL/TLOmodel/blob/67c80589a2e0f274ac12c87cd76876df3010d51d/docs/hsi_events.rst?plain=1#L17).

So here we could have the website builder create a reStructuredText file with the table of profiling results and then just directly include this on the landing page? That would also save needing to have something like the placeholder

https://github.com/UCL/TLOmodel-profiling/blob/2535dcba351db4f4bb8503a83e08c9f0a2d42612/source/profiling.rst?plain=1#L6

we have currently (as we just output to a predetermined file name and include that file rather than replacing the placeholder).

On the other hand, there is nothing specifically wrong with the current redirect solution that I can see, it just seems a bit more complex than necessary (and I guess might be somewhat device / browser dependent on whether the redirect works or not).

2024-05-22 08:42 UTC, tamuri commented
Yes, the redirect feels clunky.

2024-05-22 08:57 UTC, willGraham01 commented
My reasoning for the redirect was that it's the least noisy solution for what we initially wanted to achieve (since it saved going through the rst files and updating links), but yeah now I think about it I could've just moved the profiling results to that page :sweat_smile: 

Have also changed the `profiling.rst` (and `run-statistics.rst`) files to have the lookup table / plots `.. included:`ed from files with underscores like in the main TLO repo, rather than using the placeholders.

2024-05-22 10:07 UTC, matt-graham requested changes
Thanks @willGraham01 for the updates. Tested and this works locally and looks generally good to me, other than a couple of minor suggestions / comments.

2024-05-22 10:07 UTC, matt-graham commented on source/_profiling_table.rst
Can this file not be removed now? Deleting locally the build still seems to work without any issues.

2024-05-22 10:07 UTC, matt-graham commented on source/conf.py
Changing line 46 to
```
exclude_patterns = ["_*.rst"]
```
will prevent orphaned HTML files being generated for the `_profiling_table.rst` and `_stats_plots.rst` files that are just used as includes for other reStructuredText files (we actually don't do this currently on main `TLOmodel` docs as for example https://www.tlomodel.org/_data_sources.html exists but we probably should!).

2024-05-22 11:06 UTC, matt-graham approved these changes

2024-05-22 12:53 UTC, merged